import React, { useMemo, useState } from "react";
import { INSTITUTION_TYPES, THEMES } from "./lib/constants.js";

const OBS = import.meta.env.VITE_OBSERVATORIO_URL || "https://wlamanarchy.github.io/Observatorio-Ciudadano-de-Legalidad-y-Transparencia/";
const stages = ["Diagnóstico","Reto","Propuesta","Deliberación","Evaluación","Priorización","Votación","Respuesta","Implementación","Vigilancia","Evaluación"];
const seed = [
  {id:1,title:"Universidad pública regional y formación pertinente",scope:"Regional",theme:"Educación",stage:"Deliberación",support:684,summary:"Fortalecer oferta universitaria conectada con vocaciones productivas, científicas y sociales del territorio."},
  {id:2,title:"Plan nacional de agua y resiliencia climática",scope:"Nacional",theme:"Agua",stage:"Evaluación",support:1214,summary:"Priorizar abastecimiento, saneamiento, protección de cuencas y adaptación climática con metas verificables."},
  {id:3,title:"Red de innovación y bioeconomía territorial",scope:"Departamental",theme:"Ciencia y tecnología",stage:"Priorización",support:902,summary:"Articular universidades, comunidades, empresas y Estado alrededor de proyectos de innovación con impacto regional."}
];

export default function App(){
  const [view,setView]=useState("inicio");
  const [proposals,setProposals]=useState(seed);
  const [votes,setVotes]=useState({});
  const nav=[["inicio","Inicio"],["diagnostico","Diagnóstico"],["propuestas","Propuestas"],["proponer","Proponer"],["priorizar","Priorizar"],["metodo","Reglas"]];
  return <div className="app">
    <header className="hero"><div className="wrap"><div className="eyebrow">DEMOCRACIA PARTICIPATIVA · PLANEACIÓN PERMANENTE</div><h1>Colombia Construye Futuro</h1><p>Una plataforma para convertir diagnóstico ciudadano en propuestas, deliberación, prioridades y seguimiento institucional.</p><div className="hero-actions"><button onClick={()=>setView("proponer")}>Proponer</button><button onClick={()=>setView("priorizar")} className="secondary">Priorizar</button><a href={OBS}>Abrir Observatorio de Transparencia</a></div></div></header>
    <div className="wrap"><nav className="nav">{nav.map(([k,t])=><button className={view===k?"active":""} key={k} onClick={()=>setView(k)}>{t}</button>)}</nav>
      {view==="inicio"&&<Home setView={setView}/>} {view==="diagnostico"&&<Diagnostico/>} {view==="propuestas"&&<ProposalList proposals={proposals}/>} {view==="proponer"&&<Proponer onAdd={p=>{setProposals([{...p,id:Date.now(),stage:"Propuesta",support:0},...proposals]);setView("propuestas")}}/>} {view==="priorizar"&&<Priorizar proposals={proposals} votes={votes} setVotes={setVotes}/>} {view==="metodo"&&<Metodo/>}
    </div>
    <footer><div className="wrap">Resultados del piloto = participación consultiva y trazable. No sustituyen mecanismos jurídicos vinculantes salvo articulación formal con la autoridad competente.</div></footer>
  </div>
}
function Home({setView}){return <main><section className="loop"><h2>El ciclo permanente</h2><div className="loopline">{stages.map((s,i)=><React.Fragment key={`${s}-${i}`}><span>{s}</span>{i<stages.length-1&&<b>→</b>}</React.Fragment>)}</div><p>El seguimiento vuelve a alimentar el diagnóstico: la participación no termina con una votación.</p></section><section className="grid3"><Card title="Construir visión" text="Horizontes país, territoriales e institucionales a 10, 20, 30 o más años."/><Card title="Construir normas y planes" text="Ideas, articulados, planes, estrategias, proyectos y alianzas con control de versiones."/><Card title="Decidir prioridades" text="Métodos de votación publicados antes de cada proceso, resultados auditables y separación entre opinión ciudadana y evaluación técnica."/></section><section className="callout"><h3>La transparencia es el punto de partida</h3><p>Los hallazgos y diagnósticos del Observatorio pueden convertirse en retos de futuro, sin mezclar bases de datos ni funciones institucionales.</p><button onClick={()=>setView("diagnostico")}>Ver cómo se conecta</button></section></main>}
const Card=({title,text})=><article className="card"><h3>{title}</h3><p>{text}</p></article>;
function Diagnostico(){return <main><h2>Diagnóstico para decidir mejor</h2><div className="grid2"><Card title="1. Evidencia pública" text="Datos abiertos, planes vigentes, indicadores, fuentes oficiales y seguimiento ciudadano."/><Card title="2. Problema verificable" text="El reto debe describir qué ocurre, a quién afecta, territorio, línea base y fuente."/><Card title="3. Conexión con el Observatorio" text="Un hallazgo de legalidad o integridad puede originar un reto de reforma, mejora o prevención, pero nunca se convierte automáticamente en propuesta aprobada."/><Card title="4. Trazabilidad" text="Cada diagnóstico conserva origen, fecha, fuente, versiones, aportes y respuesta institucional."/></div><a className="linkbox" href={OBS}>Ir al Observatorio Ciudadano de Legalidad y Transparencia →</a></main>}
function ProposalList({proposals}){return <main><h2>Propuestas en construcción</h2><p className="muted">La popularidad no reemplaza la deliberación: cada propuesta muestra etapa, evidencia y reglas.</p>{proposals.map(p=><article className="proposal" key={p.id}><div className="tags"><span>{p.scope}</span><span>{p.theme}</span><span>{p.stage}</span></div><h3>{p.title}</h3><p>{p.summary}</p><div className="metrics"><b>{p.support}</b> apoyos preliminares · evaluación técnica separada · historial versionado</div></article>)}</main>}
function Proponer({onAdd}){const [v,setV]=useState({title:"",summary:"",scope:"Nacional",theme:THEMES[0],institution:"",institutionType:INSTITUTION_TYPES[0],problem:"",evidence:"",outcome:""});const set=(k,x)=>setV({...v,[k]:x});return <main><h2>Crear propuesta</h2><p className="muted">Primero problema y evidencia; después solución. Una propuesta puede ser ciudadana, territorial o institucional.</p><div className="form grid2"><Field l="Título" value={v.title} onChange={x=>set("title",x)}/><Field l="Ámbito" value={v.scope} onChange={x=>set("scope",x)} options={["Nacional","Regional","Departamental","Distrital","Municipal","Local","Institucional"]}/><Field l="Tema" value={v.theme} onChange={x=>set("theme",x)} options={THEMES}/><Field l="Tipo de institución" value={v.institutionType} onChange={x=>set("institutionType",x)} options={INSTITUTION_TYPES}/><Field l="Institución relacionada" value={v.institution} onChange={x=>set("institution",x)}/><Field l="Resultado esperado" value={v.outcome} onChange={x=>set("outcome",x)}/><Area l="Problema / diagnóstico" value={v.problem} onChange={x=>set("problem",x)}/><Area l="Resumen de la propuesta" value={v.summary} onChange={x=>set("summary",x)}/><Area l="Evidencia / fuentes" value={v.evidence} onChange={x=>set("evidence",x)}/></div><button onClick={()=>{if(v.title.trim().length<8||v.summary.trim().length<40||v.problem.trim().length<40)return alert("Completa título, diagnóstico y propuesta con suficiente detalle.");onAdd(v)}}>Guardar borrador</button></main>}
function Field({l,value,onChange,options}){return <label><span>{l}</span>{options?<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function Area({l,value,onChange}){return <label className="full"><span>{l}</span><textarea rows="4" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Priorizar({proposals,votes,setVotes}){const total=Object.values(votes).reduce((a,b)=>a+b,0);const remain=100-total;const ranked=useMemo(()=>proposals.map(p=>({...p,points:votes[p.id]||0})).sort((a,b)=>b.points-a.points),[proposals,votes]);return <main><h2>Presupuesto ciudadano de prioridades</h2><div className="rulebox"><b>100 puntos por persona</b><p>Distribúyelos entre las alternativas. En un proceso real, las reglas y el universo de propuestas se congelan antes de abrir la votación.</p><strong>Disponibles: {remain}</strong></div>{ranked.map(p=><article className="vote" key={p.id}><div><h3>{p.title}</h3><small>{p.scope} · {p.theme}</small></div><input aria-label={`Puntos para ${p.title}`} type="number" min="0" max="100" value={votes[p.id]||0} onChange={e=>{const n=Math.max(0,Math.min(100,Number(e.target.value)||0));const next={...votes,[p.id]:n};if(Object.values(next).reduce((a,b)=>a+b,0)<=100)setVotes(next)}}/><b>{votes[p.id]||0} pts</b></article>)}</main>}
function Metodo(){return <main><h2>Reglas de legitimidad</h2><div className="grid2"><Card title="Identidad y voto" text="Acceso abierto para leer y deliberar. Votaciones finales requieren nivel de verificación definido; una persona = un voto dentro del universo habilitado."/><Card title="Reglas antes del voto" text="Método, quorum, periodo, elegibilidad, territorio, tratamiento de empates y umbrales se publican y congelan antes de abrir urnas."/><Card title="Deliberación informada" text="Argumentos a favor, en contra y alternativas; evidencia enlazada; versiones; respuesta de proponentes; moderación apelable."/><Card title="Evaluación técnica separada" text="Expertos califican viabilidad, costos, riesgos e impactos, pero su criterio no multiplica el voto ciudadano."/><Card title="IA limitada y auditable" text="Puede resumir, traducir, agrupar duplicados y detectar señales de abuso. Nunca define ganadores ni elimina aportes sin control humano y recurso."/><Card title="Inclusión y accesibilidad" text="WCAG 2.1 AA como mínimo, lenguaje claro, acceso móvil, canales presenciales/offline con trazabilidad y medidas de inclusión territorial."/><Card title="Privacidad" text="Minimización de datos, consentimiento informado, separación de identidad y preferencias cuando sea posible, retención limitada y auditoría de accesos."/><Card title="No confundir consulta con decisión vinculante" text="El resultado se publica con su naturaleza jurídica. Solo será vinculante cuando se articule a un mecanismo legal que produzca ese efecto."/></div></main>}
